version: '3.8'

services: 

  django_server:
    build: ./server
    volumes: 
      - ./backend:/usr/src/app
    expose:
      - 8000

  client:
    build: ./client
    volumes: 
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    depends_on:
      - django_server

  nginx:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - django_server
      - client
    
    

