# Generated by Django 3.1.7 on 2021-04-21 02:37

import coaches.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=coaches.models.upload_location)),
                ('gender', models.CharField(max_length=25)),
                ('minPrice', models.IntegerField(default=0)),
                ('maxPrice', models.IntegerField(default=50)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('experienceDescription', models.TextField(default='')),
                ('credentialDescription', models.TextField(default='')),
                ('sessionDescription', models.TextField(default='')),
                ('trainingAddress', models.CharField(default='', max_length=200)),
                ('trainingPhone', models.CharField(default='', max_length=50)),
                ('sessionLength', models.CharField(default='', max_length=50)),
                ('remotePlatform', models.CharField(default='', max_length=50)),
                ('remote', models.BooleanField(default=False)),
                ('inPerson', models.BooleanField(default=False)),
                ('focus_life', models.BooleanField(default=False)),
                ('focus_behavioral_wellness', models.BooleanField(default=False)),
                ('focus_health_wellness', models.BooleanField(default=False)),
                ('focus_holistic', models.BooleanField(default=False)),
                ('focus_business', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('facebook', models.TextField(default='', blank=True)),
                ('instagram', models.TextField(default='', blank=True)),
                ('twitter', models.TextField(default='', blank=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
