# Generated by Django 3.1.7 on 2021-04-21 02:37

import coaches.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=coaches.models.upload_location)),
                ('gender', models.CharField(max_length=1)),
                ('focus_life', models.BooleanField(default=False)),
                ('focus_behavioral', models.BooleanField(default=False)),
                ('focus_health_wellness', models.BooleanField(default=False)),
                ('focus_holistic', models.BooleanField(default=False)),
                ('focus_nutrition_fitness', models.BooleanField(default=False)),
                ('focus_business', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
