# Generated by Django 3.1.7 on 2021-04-29 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
