# Generated by Django 3.1.7 on 2021-11-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coach',
            name='instagram',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coach',
            name='twitter',
            field=models.TextField(default=''),
        ),
    ]
