# Generated by Django 3.1.7 on 2021-04-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
